In [31]:
import pandas as pd
data = pd.read_csv("volcano_db.csv", encoding = "ISO-8859-1")
for values in ("Number", "Region", "Country", "Type", "Status", "Last Known"):
    data = data.drop(values,1)
data[340:370]

                Volcano Name  Latitude  Longitude    Elev
340                    Dofen     9.350     40.130  1151.0
341               Doma Peaks    -5.900    143.150  3568.0
342                   Domuyo   -36.630    -70.420  4709.0
343  Don Joao de Castro Bank    38.230    -26.630   -14.0
344               Dona Juana     1.470    -76.920  4150.0
345                  Dotsero    39.650   -107.030  2230.0
346                  Douglas    58.870   -153.550  2140.0
347            Doyo Seamount    27.683    140.800  -860.0
348                    Dubbi    13.580     41.808  1625.0
349                   Dukono     1.680    127.880  1185.0
350             Duncan Canal    56.500   -133.100    15.0
351       Durango Volc Field    24.150   -104.450  2075.0
352                   Dutton    55.180   -162.270  1506.0
353               Dzenzursky    53.637    158.922  2155.0
354                    E-san    41.800    141.170   618.0
355         Eagle Lake Field    40.630   -120.830  1652.0
356            Easter Island   -27.150   -109.383   511.0
357  Eastern Gemini Seamount   -20.980    170.280   -80.0
358                    Ebeko    50.680    156.020  1156.0
359                  Ebulobo    -8.808    121.180  2124.0
360        Eburru, Ol Doinyo    -0.630     36.230  2856.0
361          Ecuador, Volcan    -0.020    -91.546   790.0
362                Edgecumbe    57.050   -135.750   976.0
363                   Edziza    57.720   -130.630  2786.0
364                  Eggella    56.570    158.520  1046.0
365                   Egmont   -39.300    174.070  2518.0
366                     Egon    -8.670    122.450  1703.0
367                   Ekarma    48.958    153.930  1170.0
368                   Elbrus    43.330     42.450  5633.0
369      Elmenteita Badlands    -0.520     36.270  2126.0

In [32]:
data["Volcano Name"].str.replace("'","")

0                       Abu
1                Acamarachi
2                Acatenango
3           Acigol-Nevsehir
4                     Adams
5                   Adatara
6                      Adwa
7                    Afdera
8           Agmagan-Karadag
9                   Agrigan
10                     Agua
11              Agua de Pau
12                 Aguilera
13                    Agung
14                     Ahyi
15            Akademia Nauk
16            Akademia Nauk
17                    Akagi
18                     Akan
19                  Akhtang
20        Akita-Komaga-take
21          Akita-Yake-yama
22             Akuseki-jima
23             Akuseki-jima
24                   Akutan
25                    Alaid
26                 Alamagan
27                   Alayta
28            Albano, Monte
29           Alcedo, Volcan
               ...
1541               Yanteles
1542        Yanteles, Cerro
1543             Yar, Jabal
1544                  Yasur
1545                   Yate
1546                  Yelia
1547            Yellowstone
1548                 Yersey
1549            Yojoa, Lake
1550                  Yomba
1551                  Yotei
1552           Young Island
1553               Yucamane
1554           Yumia, Cerro
1555                Yunaska
1556    Zacate Grande, Isla
1557                    Zao
1558               Zaozerny
1559               Zapatera
1560             Zavaritsky
1561             Zavaritsky
1562     Zavaritzki Caldera
1563             Zavodovski
1564                 Zengyu
1565             Zheltovsky
1566            Zhupanovsky
1567                 Zimina
1568          Zubair, Jebel
1569                  Zukur
1570           Zuni-Bandera
Name: Volcano Name, Length: 1571, dtype: object

In [17]:
data.index

RangeIndex(start=0, stop=1571, step=1)

In [30]:
import numpy as np
intervals = np.arange(0, data.index.max(), 50)
intervals[-1]

1550

In [33]:
help(folium.Icon())

NameError: name 'folium' is not defined